### ISSUE TITLE
Change from wercker CI to github actions

### ISSUE THREAD

**Issue by kartikmohta** [KumarRobotics/kr_mav_control#135]
Wercker doesn't seem to be working well these days, and since this is now open-source, better to just use github actions.

**Comment by tdinesh** [comment]
Sounds good to me

**Comment by tdinesh** [comment]
Lets use [ROS CI action](https://github.com/marketplace/actions/ros-2-ci-action)?

**Comment by kartikmohta** [comment]
It looks ok but requires specifying each package individually in the `package-name` option, not ideal for our case.

**Comment by tdinesh** [comment]
Any other examples that you know of? Else, have to start from scratch.

**Comment by kartikmohta** [comment]
All the steps required are in the `wercker.yml` already, could it be so hard to do our own? (I haven't checked the docs yet)

**Comment by kartikmohta** [comment]
Looked at a simple example here: https://github.com/actions/starter-workflows/blob/main/ci/cmake.yml
Seems simple enough to copy the steps from `wercker.yaml` to this format.

**Comment by tdinesh** [comment]
Ok, will give it a try.

**Comment by tdinesh** [comment]
Addressed in #137
