### ISSUE TITLE
mavros interface for trajectory tracker

### ISSUE THREAD

**Issue by shubham-shahh** [KumarRobotics/kr_mav_control#147]
Hi,
I want to pass the SO3 command to the FCU via mavros, I checked the AttitudeTarget message, but that message only supports normlised thrust in z-axis, but SO3Command has forces in x, y and z axis. how can I convert SO3Command to Attitude target message @kartikmohta 

thanks

**Comment by jessweakly** [comment]
This is an old thread so hopefully you have gotten the info you need, but I'm putting a response here in case someone has the same question. 

This should be handled already in kr_mavros_interface. Check out line 123 in particular. You will need to update the kf parameter based on your robot. https://github.com/KumarRobotics/kr_mav_control/blob/master/interfaces/kr_mavros_interface/src/so3cmd_to_mavros_nodelet.cpp

**Comment by fcladera** [comment]
Thanks @jessweakly!!
