### ISSUE TITLE
Question about the Thrust Models in Mavros Interface

### ISSUE THREAD

**Issue by mzahana** [KumarRobotics/kr_mav_control#156]
Hi @tdinesh 

Thanks for the great work!

I saw different thrust models in the mavros interface [here](https://github.com/KumarRobotics/kr_mav_control/blob/fla_mavros_interface/interfaces/kr_mavros_interface/src/so3cmd_to_mavros_nodelet.cpp)

I would like to ask if there is any document/paper that explains the math behind this implementation. Also, which one works better in your experience , the implementation in the `master` branch or the one I linked above in the `fla_mavros_interface` branch?

Thank you.

**Comment by fcladera** [comment]
Hi! We use generally the `KARTIK`, which is an open-loop approximation that models thrust as a function of angular speed. We usually get the thrust curves with a [thrust stand](https://www.tytorobotics.com/), where you input a speed command to the ESC and you can evaluate the thrust that is produced by your motor-prop combination. 

This is an example for the ModalAI starling https://forum.modalai.com/topic/2521/propeller-coefficients-for-starling-v2/2?_=1708124302844
